#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Tala on the App Store, without a Mac: everything Apple needs once, so that
# .github/workflows/ios.yml can build, sign and upload to TestFlight on its own.
# Values are kept in ~/.tala-ios (outside the repo: these are signing keys).
# Re-run any time; it remembers what you already entered. Yearly: the
# distribution certificate expires, so re-run stage 4 then.

TOTAL_STAGES=9
TALA_DIR="$HOME/.tala-ios"
mkdir -p "$TALA_DIR" && chmod 700 "$TALA_DIR"
ENV_FILE="$TALA_DIR/ios.env"
cd "$(git rev-parse --show-toplevel)"

# A WSL path the Windows browser can upload from / that a download landed in
winpath() { if command -v wslpath >/dev/null 2>&1; then wslpath -w "$1"; else printf '%s' "$1"; fi; }
unixpath() { if command -v wslpath >/dev/null 2>&1 && [[ "$1" == *:\\* ]]; then wslpath -u "$1"; else printf '%s' "$1"; fi; }

banner "Tala → TestFlight setup"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Join the Apple Developer Program"
say "Publishing on the App Store needs a paid membership (US\$99 a year)."
open_url "https://developer.apple.com/programs/enroll/"
step "Sign in with your Apple ID (two-factor authentication must be on)."
step "Enroll as an Individual. Your legal name becomes the seller name on the App Store."
step "Pay, then wait for the 'Welcome to the Apple Developer Program' email (minutes to 2 days)."
pause "Press Enter once your membership is active"

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Team ID"
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Account → Membership details → copy the Team ID (10 letters and digits)."
ask APPLE_TEAM_ID "Paste the Team ID:"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_secret APPLE_TEAM_ID "$APPLE_TEAM_ID"

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Register the app's identifier"
open_url "https://developer.apple.com/account/resources/identifiers/add/bundleId"
step "Choose App IDs → Continue → App → Continue."
step "Description: Tala.   Bundle ID: Explicit → com.lanz.tala"
step "Leave every capability off (Tala needs none) → Continue → Register."
note "Already registered? Skip ahead."
pause "Press Enter when com.lanz.tala is listed under Identifiers"

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Apple Distribution certificate (made here, no Mac)"
say "One certificate that every CI run reuses. Its private key never leaves $TALA_DIR."
ask APPLE_ID_EMAIL "Your Apple ID email:"
write_env APPLE_ID_EMAIL "$APPLE_ID_EMAIL"
if [[ ! -f "$TALA_DIR/dist.key" ]]; then
  openssl genrsa -out "$TALA_DIR/dist.key" 2048 2>/dev/null
  chmod 600 "$TALA_DIR/dist.key"
fi
openssl req -new -key "$TALA_DIR/dist.key" -out "$TALA_DIR/dist.csr" -subj "/emailAddress=$APPLE_ID_EMAIL/CN=Tala Distribution/C=PH"
cp "$TALA_DIR/dist.csr" "/tmp/tala-dist.csr"
say "Certificate request: $(winpath /tmp/tala-dist.csr)"
open_url "https://developer.apple.com/account/resources/certificates/add"
step "Choose Apple Distribution → Continue."
step "Upload the request file above (paste its path into the file picker) → Continue."
step "Download the certificate (distribution.cer)."
ask DIST_CER_PATH "Path of the downloaded .cer (a Windows path is fine):"
DIST_CER_PATH=$(unixpath "$DIST_CER_PATH")
cp "$DIST_CER_PATH" "$TALA_DIR/distribution.cer"
openssl x509 -inform DER -in "$TALA_DIR/distribution.cer" -out "$TALA_DIR/distribution.pem"
IOS_DIST_P12_PASSWORD=$(_existing IOS_DIST_P12_PASSWORD || openssl rand -base64 18)
# SHA1/3DES: the encryption macOS's `security import` reads (OpenSSL 3's default it rejects)
openssl pkcs12 -export -inkey "$TALA_DIR/dist.key" -in "$TALA_DIR/distribution.pem" \
  -out "$TALA_DIR/distribution.p12" -name "Tala Distribution" -passout "pass:$IOS_DIST_P12_PASSWORD" \
  -certpbe PBE-SHA1-3DES -keypbe PBE-SHA1-3DES -macalg sha1
chmod 600 "$TALA_DIR/distribution.p12"
rm -f /tmp/tala-dist.csr
write_env IOS_DIST_P12_PASSWORD "$IOS_DIST_P12_PASSWORD"
set_secret IOS_DIST_P12_PASSWORD "$IOS_DIST_P12_PASSWORD"
set_secret IOS_DIST_P12_BASE64 "$(base64 -w0 "$TALA_DIR/distribution.p12")"

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "App Store Connect API key"
say "Lets CI fetch a provisioning profile and upload builds without your password."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Team Keys tab (the first time, click 'Request Access' and accept)."
step "Generate API Key → Name: Tala CI → Access: Admin → Generate."
note "Admin is required: Xcode's signing step is refused with Developer or App Manager keys."
step "Copy the Issuer ID shown above the table."
ask ASC_ISSUER_ID "Paste the Issuer ID:"
step "Copy the Key ID of the new key."
ask ASC_KEY_ID "Paste the Key ID:"
step "Download API Key (.p8). Apple lets you download it only once."
ask ASC_KEY_PATH "Path of the downloaded AuthKey_….p8 (a Windows path is fine):"
ASC_KEY_PATH=$(unixpath "$ASC_KEY_PATH")
cp "$ASC_KEY_PATH" "$TALA_DIR/AuthKey.p8" && chmod 600 "$TALA_DIR/AuthKey.p8"
write_env ASC_ISSUER_ID "$ASC_ISSUER_ID"
write_env ASC_KEY_ID "$ASC_KEY_ID"
set_secret ASC_ISSUER_ID "$ASC_ISSUER_ID"
set_secret ASC_KEY_ID "$ASC_KEY_ID"
set_secret ASC_KEY_P8 "$(cat "$TALA_DIR/AuthKey.p8")"

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Privacy policy page"
say "Every App Store app needs a privacy policy URL, even one that collects nothing."
say "public/privacy.html ships with the web build, so it is live once the site is deployed."
open_url "https://tala.lorenzmalabanan.com/privacy.html"
pause "Press Enter once the page loads (deploy the site first if it doesn't)"

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Create the app in App Store Connect"
open_url "https://appstoreconnect.apple.com/apps"
step "+ → New App → Platform: iOS."
step "Name: Tala: Notebook & Planner   (taken? try: Tala — Pagtatala)"
step "Primary language: English (U.S.) · Bundle ID: com.lanz.tala · SKU: tala-ios · Full Access → Create."
step "App Privacy → Privacy Policy URL: https://tala.lorenzmalabanan.com/privacy.html"
step "App Privacy → Get Started → 'No, we do not collect data from this app' → Publish."
pause "Press Enter when the app exists"

# ── 8 ──────────────────────────────────────────────────────────────────────
stage "First TestFlight build"
say "ios.yml runs on a GitHub macOS runner (free on this public repo): build, sign, upload."
note "GitHub only offers 'Run workflow' once ios.yml is on the default branch (main)."
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if confirm "Start the iOS workflow on '$BRANCH' now?"; then
  if gh workflow run ios.yml --ref "$BRANCH"; then
    open_url "https://github.com/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/workflows/ios.yml"
    step "Wait for the green check (about 15 minutes). Apple then processes the build (10-30 minutes more)."
  else
    SKIPPED+=("start the iOS workflow: merge to main, then: gh workflow run ios.yml")
  fi
else
  SKIPPED+=("start the iOS workflow: gh workflow run ios.yml (or push a v* tag)")
fi
pause

# ── 9 ──────────────────────────────────────────────────────────────────────
stage "Install it on your iPad or iPhone"
open_url "https://appstoreconnect.apple.com/apps"
step "Tala → TestFlight → Internal Testing → + → group name: Me → add yourself."
step "Turn on automatic distribution, so every new build reaches the group."
step "On the iPad/iPhone: install TestFlight from the App Store, open the invite email."
note "Test: airplane mode, Apple Pencil, back up (share sheet), lecture audio."
pause "Press Enter to finish"

finish
